name: Test

on:
  push:
    branches-ignore:
      - automated/*
      - renovate/*
    paths-ignore:
      - .editorconfig
      - .gitignore
      - .markdownlint.yaml
      - .trunk/**
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test:
    name: Test

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Fetch Git tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 2.12.2 # datasource=github-releases depName=goreleaser/goreleaser
          args: build --clean --snapshot --single-target --output aws-eks-get-token

      - name: Test the output
        run: |-
          ./aws-eks-get-token 2>&1 | grep "Error: either --cluster-name or --cluster-id must be specified"
